api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    # users authentication and authoration
	path('users/',views.ListUsers.as_view(),name='users'),
	path('register/',views.CreateUser.as_view(),name="api-register"),
	path('token/',views.CustomTokenObtainPairView.as_view(),name="token_obtain_pair"),
	path('token/refresh/',TokenRefreshView.as_view(),name="token_refresh"),
    path('password-change/',views.UserPasswordChangeView.as_view(),name="password-change"),
    path('password-reset/',views.UserPasswordResetEmailView.as_view(),name="password-reset-email"),
    path('password-reset/<uuid:user_id>/',views.UserPasswordResetView.as_view(),name="password-reset"),

    # anon users authentication and authoration
    path('token2/',views.CustomTokenObtainPairForAnonUserView.as_view(),name="token_obtain_pair"),
    path('token2/refresh/',TokenRefreshView.as_view(),name="token_refresh"),

    # post
    path('get-post/',views.GetPost.as_view(),name="get-post"),
    path('get-post/<uuid:pk>/',views.GetPostById.as_view(),name="get-post-by-id"),
	path('create-post/',views.CreatePostView.as_view(),name="create-post"),
	path('get-comment/',views.GetComment.as_view(),name="get-comment"),
	path('get-comment/<int:pk>/',views.GetCommentById.as_view(),name="get-comment-by-id"),
	path('create-comment/',views.CreateComment.as_view(),name="create-comment"),

    # articel urls
    path('create-article/',views.CreateArticle.as_view(),name="create-article"),
    path('get-article/',views.GetArticle.as_view(),name="get-article"),
    path('get-article/<int:pk>/',views.GetArticleById.as_view(),name="get-article-by-id"),
    path('create-article-comment/',views.CreateArticleComment.as_view(),name="create-article-comment"),
    path('article-comments/',views.ArticleComments.as_view(),name='article-comments'),

    # like urls
    path('like-post/',views.LikePost.as_view(),name="like-post"),
    path('like-article/',views.LikeArticle.as_view(),name="like-article"),

    # following urls
    path('follow/',views.FollowView.as_view(),name="follow"),
]

base/urls.py
from django.urls import path,re_path
from . import views
from . import errors
from django.utils.text import slugify
from urllib.parse import quote,unquote, quote_plus
import re

app_name = "base"

urlpatterns = [
	path('',views.Main.as_view(),name="main"),
	path('search_query/',views.SearchView.as_view(),name="search"),
	path('register/',views.Register.as_view(),name="register"),
	path('login/',views.Login.as_view(),name="login"),
	path('logout/',views.logout_view,name="logout"),
	path('password-change/',views.UserPasswordChangeView.as_view(),name="password_change_view"),
	path('password-reset/',views.UserPasswordResetView.as_view(),name="password-reset"),
	path('password-reset-done/',views.UserPasswordResetDoneView.as_view(),name="password-reset-done"),
	path('reset/<uidb64>/<token>',views.UserPasswordResetConfirmView.as_view(),name="password-reset-confirm"),
	path('password-reset-complete/',views.UserPasswordResetCompleteView.as_view(),name="password-reset-complete"),
	path('<slug:user>-<uidb64>/dashboard/',views.DashboardView.as_view(),name="dashboard"),
	path('comment/<str:post_id>/',views.PostCommentView.as_view(),name="post-comment-view"),
	path('comment-article/<int:pk>/',views.PostCommentArticleView.as_view(),name="article-comment-view"),
	path('like/<str:post_id>/',views.LikePostView.as_view(),name="like-post"),
	path('create-article/',views.CreateArticleView.as_view(),name="create-article"),
	path('articles/',views.ShowArticles.as_view(),name="articles"),
	path('article/<str:pk>/',views.ArticleDetailView.as_view(),name="article-detail"),
	path('article-edit/<int:pk>/',views.EditArticleView.as_view(),name="edit-article"),
	path('article-delete/<article>/',views.DeleteArticleView.as_view(),name="delete-article"),
	path('like-article/<int:pk>/',views.LikeArticleView.as_view(),name="like-article"),

	# post
	path('post-edit/<uuid:post><str:user_id>/',views.EditPostView.as_view(),name="edit-post"),
	path('post-delete/<uuid:post><str:user_id>/',views.DeletePostView.as_view(),name="delete-post"),
	path('posts/post-<uuid:post_id>/',views.ExplorePostView.as_view(),name="explore-post"),

	# anon user
	path('auto-login/anon-user/',views.login_as_ordinary_user,name="auto-anonuser-login"),

	# user
	path('users/<str:username>/<str:user_id>/',views.UserProfileShowcaseView.as_view(),name="user-profile-showcase"),
	path('follow/<str:name>/<str:user_id>/',views.FollowView.as_view(),name="follow"),

	# appoinment urls here
	path('appointment/detail/<str:response_type>/<int:client_id>/',views.AppointmentView.as_view(),name="appointment-detail"),
	path('appointment/<doctor_id>/',views.MakeAppointmentView.as_view(),name="appointment"),
    path('appointments/list/',views.ListAppointmentsView.as_view(),name="appointments-list"),

	# chat
	path('chat/',views.ChatRoomView.as_view(),name="chat-room"),
	path('chat/<str:user_id>/',views.ChatRoomView.as_view(),name="chat-room"),
	path('room/',views.chat_api,name="chat-api"),

	# video stream
	path('live-stream/',views.LiveStreamView.as_view(),name="live-stream"),
 	path('live-stream/<user_id>/',views.LiveStreamView.as_view(),name="live-stream"),

	# saved messages
	path('collections/',views.SavedMessagesView.as_view(),name="saved-messages"),
	path('collections/<str:message_type>/<str:message_id>/',views.SavedMessagesDetailAndCreateView.as_view(),name="saved-messages-detail-create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('api/',include('api.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
]

handler403 = "base.errors.error_403"
handler404 = "base.errors.error_404"
handler500 = "base.errors.error_500"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
#else:
#    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

frontend/templates/pages/articles/article_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex justify-content-center" style="margin-top: 50px;">
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ article }}"?</p>
        {{ form }}
        <button class="btn btn-danger" type="submit">Yes, I'm sure</button>
        <a href="{{back}}"><button class="btn btn-secondary" type="button">No, take me back</button></a>
    </form>
</div>
{% endblock %}

frontend/templates/pages/articles/edit_article.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	
<div class="card">
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<button class="btn btn-primary" type="submit">Save</button>
	</form>
</div>

{% endblock %}

frontend/templates/pages/articles/show_articles.html
{% extends "base.html" %}
{% block content %}

<div class="d-flex justify-content-center justify-content-md-center mb-3">
	<div style="width: 750px;">
		<a href="{% url 'base:create-article' %}" style="text-decoration: none;"><input type="text" class="form-control" placeholder="Write article..." style="width:700px;margin-top: 15px;" /></a>
        {% if articles|length != 0 %}
            {% for article in articles %}
            	<div class="shadow-sm bg-white" style="width: 700px; padding: 5px 5px; margin-top:20px;border-radius: 10px;">
			<a href="{% url 'base:article-detail' article.pk %}"><article>{{article.headline}}</article></a>
	                <div style="max-width: 690px;margin-top:20px;">
	                    {{article.body|safe|truncatechars:400}}
	                </div>
	        </div>
            {% endfor %}
        {% else %}
            <h3 style="margin-left: 80px;">No articles yet</h3>
        {% endif %}
    </div>
</div>
{% endblock %}