api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    # users authentication and authoration
	path('users/',views.ListUsers.as_view(),name='users'),
	path('register/',views.CreateUser.as_view(),name="api-register"),
	path('token/',views.CustomTokenObtainPairView.as_view(),name="token_obtain_pair"),
	path('token/refresh/',TokenRefreshView.as_view(),name="token_refresh"),
    path('password-change/',views.UserPasswordChangeView.as_view(),name="password-change"),
    path('password-reset/',views.UserPasswordResetEmailView.as_view(),name="password-reset-email"),
    path('password-reset/<uuid:user_id>/',views.UserPasswordResetView.as_view(),name="password-reset"),

    # anon users authentication and authoration
    path('token2/',views.CustomTokenObtainPairForAnonUserView.as_view(),name="token_obtain_pair"),
    path('token2/refresh/',TokenRefreshView.as_view(),name="token_refresh"),

    # post
    path('get-post/',views.GetPost.as_view(),name="get-post"),
    path('get-post/<uuid:pk>/',views.GetPostById.as_view(),name="get-post-by-id"),
	path('create-post/',views.CreatePostView.as_view(),name="create-post"),
	path('get-comment/',views.GetComment.as_view(),name="get-comment"),
	path('get-comment/<int:pk>/',views.GetCommentById.as_view(),name="get-comment-by-id"),
	path('create-comment/',views.CreateComment.as_view(),name="create-comment"),

    # articel urls
    path('create-article/',views.CreateArticle.as_view(),name="create-article"),
    path('get-article/',views.GetArticle.as_view(),name="get-article"),
    path('get-article/<int:pk>/',views.GetArticleById.as_view(),name="get-article-by-id"),
    path('create-article-comment/',views.CreateArticleComment.as_view(),name="create-article-comment"),
    path('article-comments/',views.ArticleComments.as_view(),name='article-comments'),

    # like urls
    path('like-post/',views.LikePost.as_view(),name="like-post"),
    path('like-article/',views.LikeArticle.as_view(),name="like-article"),

    # following urls
    path('follow/',views.FollowView.as_view(),name="follow"),
]

base/urls.py
from django.urls import path,re_path
from . import views
from . import errors
from django.utils.text import slugify
from urllib.parse import quote,unquote, quote_plus
import re

app_name = "base"

urlpatterns = [
	path('',views.Main.as_view(),name="main"),
	path('search_query/',views.SearchView.as_view(),name="search"),
	path('register/',views.Register.as_view(),name="register"),
	path('login/',views.Login.as_view(),name="login"),
	path('logout/',views.logout_view,name="logout"),
	path('password-change/',views.UserPasswordChangeView.as_view(),name="password_change_view"),
	path('password-reset/',views.UserPasswordResetView.as_view(),name="password-reset"),
	path('password-reset-done/',views.UserPasswordResetDoneView.as_view(),name="password-reset-done"),
	path('reset/<uidb64>/<token>',views.UserPasswordResetConfirmView.as_view(),name="password-reset-confirm"),
	path('password-reset-complete/',views.UserPasswordResetCompleteView.as_view(),name="password-reset-complete"),
	path('<slug:user>-<uidb64>/dashboard/',views.DashboardView.as_view(),name="dashboard"),
	path('comment/<str:post_id>/',views.PostCommentView.as_view(),name="post-comment-view"),
	path('comment-article/<int:pk>/',views.PostCommentArticleView.as_view(),name="article-comment-view"),
	path('like/<str:post_id>/',views.LikePostView.as_view(),name="like-post"),
	path('create-article/',views.CreateArticleView.as_view(),name="create-article"),
	path('articles/',views.ShowArticles.as_view(),name="articles"),
	path('article/<str:pk>/',views.ArticleDetailView.as_view(),name="article-detail"),
	path('article-edit/<int:pk>/',views.EditArticleView.as_view(),name="edit-article"),
	path('article-delete/<article>/',views.DeleteArticleView.as_view(),name="delete-article"),
	path('like-article/<int:pk>/',views.LikeArticleView.as_view(),name="like-article"),

	# post
	path('post-edit/<uuid:post><str:user_id>/',views.EditPostView.as_view(),name="edit-post"),
	path('post-delete/<uuid:post><str:user_id>/',views.DeletePostView.as_view(),name="delete-post"),
	path('posts/post-<uuid:post_id>/',views.ExplorePostView.as_view(),name="explore-post"),

	# anon user
	path('auto-login/anon-user/',views.login_as_ordinary_user,name="auto-anonuser-login"),

	# user
	path('users/<str:username>/<str:user_id>/',views.UserProfileShowcaseView.as_view(),name="user-profile-showcase"),
	path('follow/<str:name>/<str:user_id>/',views.FollowView.as_view(),name="follow"),

	# appoinment urls here
	path('appointment/detail/<str:response_type>/<int:client_id>/',views.AppointmentView.as_view(),name="appointment-detail"),
	path('appointment/<doctor_id>/',views.MakeAppointmentView.as_view(),name="appointment"),
    path('appointments/list/',views.ListAppointmentsView.as_view(),name="appointments-list"),

	# chat
	path('chat/',views.ChatRoomView.as_view(),name="chat-room"),
	path('chat/<str:user_id>/',views.ChatRoomView.as_view(),name="chat-room"),
	path('room/',views.chat_api,name="chat-api"),

	# video stream
	path('live-stream/',views.LiveStreamView.as_view(),name="live-stream"),
 	path('live-stream/<user_id>/',views.LiveStreamView.as_view(),name="live-stream"),

	# saved messages
	path('collections/',views.SavedMessagesView.as_view(),name="saved-messages"),
	path('collections/<str:message_type>/<str:message_id>/',views.SavedMessagesDetailAndCreateView.as_view(),name="saved-messages-detail-create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('api/',include('api.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
]

handler403 = "base.errors.error_403"
handler404 = "base.errors.error_404"
handler500 = "base.errors.error_500"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
#else:
#    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

frontend/templates/pages/appointment_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% if appointments_count != 0 %}
<div class="d-flex justify-content-center justify-content-md-center mb-3" style="flex-direction: column;align-items: center;">
   <h3 style="text-align:center;">Appointments</h3>
   {% for appointment in appointments %}
   <div class="form-group col-md-4 shadow-sm border rounded p-4 mb-4 bg-white">
	<b>Doctor:</b>  <span><a href="{% url 'base:user-profile-showcase' appointment.doctor.name appointment.doctor.id %}">{{ appointment.doctor.name }}</a></span>
	<h5>Reason</h5>
	<p>{{appointment.reason}}</p>

{% if appointment.approved %}
	<h5>Response from doctor</h5>
	<p>{{ appointment.text }}</p>
{% endif %}
	<h5>Status</h5>
{% if appointment.approved %}
	<b style="color: green;">Approved</b>
{% elif appointment.rejected %}
	<b style="color: red;">Rejected</b>
{% else %}
	<b style="color: grey;">Pending</b>
{% endif %}

<br>
<br>
<p>Created at:  <i>{{appointment.date}}</i></p>

<span><a href="{% url 'base:appointment' appointment.doctor.id %}">Edit</a></span>
   </div>
   {% endfor %}
</div> 
{% else %}
   <h1 style="text-align: center;">No appointments yet</h1>
{% endif %}

{% endblock %}

frontend/templates/pages/article_detail.html
{% extends "base.html" %}
{% load custom_tags %}

{% block content %}
    <div style="text-align: center;">
      {% if messages %}
        {% for message in messages %}
          {% if message.level == 30 %}
            <p style="color: red;">{{ message }}<a href="{% url 'base:auto-anonuser-login' %}"></a></p>
            <p> Please <a href="{% url 'base:auto-anonuser-login' %}">click</a> to login</p>
          {% elif message.level == 40 %}
            <p style="color: red;">{{ message }}<a href="{% url 'base:auto-anonuser-login' %}"></a></p>
          {% endif %}
        {% endfor %}
      {% endif %}
    </div>
    <div class="container card" style="width:650px;">
      <div style="display: flex;margin-top: 10px;">
        <img src="{{article.author.image.url}}" style="width:55px;height: 55px;border-radius: 100%;object-fit: cover;">
        <div>
          <h4><b>Dr.</b>{{article.author.name}}</h4>
	  <a href="{% url 'base:article-detail' article.id %}"><small class="text-muted">{{ article.date }} <i class="fa fa-eye" aria-hidden="true"></i>     {{article.views_count}}</small></a>
        </div>
        {% if request.user == article.author %}
          <div class="dropdown" style="margin-left: 370px;">
            <i class="fas fa-ellipsis-h" id="dropdownMenuLink" onmouseover="this.style.color='blue'" onmouseout="this.style.color='black'" style="font-size:20px;cursor: pointer;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size:20px;cursor: pointer;"></i>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="margin-left: -140px;">
              <a class="dropdown-item" href="{% url 'base:edit-article' article.id %}"><i class="fas fa-edit"></i> Edit</a>
              <a class="dropdown-item" href="{% url 'base:delete-article' article.id %}"><i class="fas fa-trash-alt"></i> Delete</a>
              <a class="dropdown-item" href="{% url 'base:saved-messages-detail-create' 'article' article.id %}"><i class="far fa-bookmark"></i>  Add to collections</a>
            </div>
          </div>

        {% else %}
          <div class="dropdown" style="margin-left: 370px;">
            <i class="fas fa-ellipsis-h" id="dropdownMenuLink" onmouseover="this.style.color='blue'" onmouseout="this.style.color='black'" style="font-size:20px;cursor: pointer;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="margin-left: -140px;">
              <a class="dropdown-item" href="{% url 'base:saved-messages-detail-create' 'article' article.id %}"><i class="far fa-bookmark"></i>  Add to collections</a>
            </div>
          </div>
        {% endif %}
      </div>
      <headline style="font-size: 26px;">{{article.headline}}</headline>
        <br>
        <body>{{article.body|safe}}</body>
        <div class="card-footer bg-white">
      {% for comment in article.article_comment.all %}
      <b>
        {% if comment.user != None %}
          {{comment.user}}
        {% else %}
          {{comment.anon_user}}
        {% endif %}
      </b>
        {% for c in comment.comment.all %}
          <p>{{c.content}} <em> {{c.date}}</em></p>
        {% endfor %}
      {% endfor %}
      <form method="post" action="{% url 'base:article-comment-view' article.id %}">
        {% csrf_token %}
        <input type="text" name="comment-text" style="width:400px;">
        <button style="height:30px;width: 50px;border: 0;border-radius: 5px;background-color: blue;color: white;" type="submit">Post</button>
      </form>
      <hr>
      <div class="row">
        <div class="col-sm d-flex justify-content-center">
          <form method="get">
          <a href="/like-article/{{article.id}}/" style="color:black;">
            {% if request|filter_user%}
              {% if article.likes.all %}
                <i class="fa{{article.likes.all|filter_like}} fa-thumbs-up" style="font-size: 30px;"></i>
              {% else %}
                <i class="far fa-thumbs-up" style="font-size: 30px;"></i>
              {% endif %}
            {% endif %}
          </a>
          <em>{{article.likes.all.count}}</em>
          </form>
        </div>
        <div class="col-sm  d-flex justify-content-center" style="color:black;" data-toggle="modal"
          data-target="#exampleModalCenter2" id="comment">
          <i class="far fa-comments" style="font-size: 30px;"><input type="hidden" value="{{post.post_id}}"></i>
        </div>
        <div class="col-sm d-flex justify-content-center"><a href="#" style="color:black;"><i
              class="far fa-share-square" style="font-size: 30px;"></i></a></div>
      </div>
    </div>
    </div>
    <hr style="margin-left:100px;margin-right:100px;">
    <div style="margin-left: 300px; margin-right: 300px;">
      <h2 style="margin-left: 200px;margin-right: 200px;">Related articles</h2>
      <div>
        {% for related_article in related_articles %}
          <a href="{% url 'base:article-detail' related_article.id %}"><h5>{{related_article.headline}}</h5></a>
          {{article.body|safe|truncatechars:400}}
        {% endfor %}
      </div>
    </div>
{% endblock %}

frontend/templates/pages/collections.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load custom_tags %}

{% block content %}
	{% if saved_messages|length == 0 %}
		<h2 style="text-align:center;margin-top:100px;">No collections yet.</h2>
	{% endif %}
	{% for saved_message in saved_messages %}
		{% for article in saved_message.articles.all %}
			<div class="container card" style="width:650px;">
		      <div style="display: flex;margin-top: 10px;">
		        <img src="{{article.author.image.url}}" style="width:55px;height: 55px;border-radius: 100%;object-fit: cover;">
		        <div>
		          <h4><b>Dr.</b>{{article.author.name}}</h4>
		          <a href="{% url 'base:article-detail' article.id %}"><small class="text-muted">{{ article.date }}</small></a></h5>
		        </div>
		        {% if request.user == article.author %}
		          <div class="dropdown" style="margin-left: 390px;">
		            <i class="fas fa-ellipsis-h" id="dropdownMenuLink" onmouseover="this.style.color='blue'" onmouseout="this.style.color='black'" style="font-size:20px;cursor: pointer;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size:20px;cursor: pointer;"></i>

		            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="margin-left: -140px;">
				    <a class="dropdown-item" href="{% url 'base:edit-article' article.id %}"><i class="fas fa-edit"></i>  Edit</a>
				    <a class="dropdown-item" href="{% url 'base:delete-article' article.id %}"><i class="fas fa-trash-alt"></i>  Delete</a>
		            </div>
		          </div>

		        {% else %}
		          <div class="dropdown" style="margin-left: 390px;">
		            <i class="fas fa-ellipsis-h" id="dropdownMenuLink" onmouseover="this.style.color='blue'" onmouseout="this.style.color='black'" style="font-size:20px;cursor: pointer;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>

		            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="margin-left: -140px;"> 
		              <a class="dropdown-item" href="{% url 'base:saved-messages-detail-create' 'article' article.id %}"><i class="far fa-bookmark"></i>  Add to collections</a>
		            </div>
		          </div>
		        {% endif %}
		      </div>
		      <headline style="font-size: 26px;">{{article.headline}}</headline>
		        <br>
		        <body>{{article.body|safe}}</body>
		        <div class="card-footer bg-white">
		      {% for comment in article.article_comment.all %}
		      <b>
		        {% if comment.user != None %}
		          {{comment.user}}
		        {% else %}
		          {{comment.anon_user}}
		        {% endif %}
		      </b>
		        {% for c in comment.comment.all %}
		          <p>{{c.content}} <em> {{c.date}}</em></p>
		        {% endfor %}
		      {% endfor %}
		      <form method="post" action="{% url 'base:article-comment-view' article.id %}">
		        {% csrf_token %}
		        <input type="text" name="comment-text" style="width:400px;">
		        <button style="height:30px;width: 50px;border: 0;border-radius: 5px;background-color: blue;color: white;" type="submit">Post</button>
		      </form>
		      <hr>
		      <div class="row">
		        <div class="col-sm d-flex justify-content-center">
		          <form method="get">
		          <a href="/like-article/{{article.id}}/" style="color:black;">
		            {% if request|filter_user%}
		              {% if article.likes.all %}
		                <i class="fa{{article.likes.all|filter_like}} fa-thumbs-up" style="font-size: 30px;"></i>
		              {% else %}
		                <i class="far fa-thumbs-up" style="font-size: 30px;"></i>
		              {% endif %}
		            {% endif %}
		          </a>
		          <em>{{article.likes.all.count}}</em>
		          </form>
		        </div>
		        <div class="col-sm  d-flex justify-content-center" style="color:black;" data-toggle="modal"
		          data-target="#exampleModalCenter2" id="comment">
		          <i class="far fa-comments" style="font-size: 30px;"><input type="hidden" value="{{post.post_id}}"></i>
		        </div>
		        <div class="col-sm d-flex justify-content-center"><a href="#" style="color:black;"><i
		              class="far fa-share-square" style="font-size: 30px;"></i></a></div>
		      </div>
		    </div>
			</div>
		{% endfor %}
		{% for post in saved_message.posts.all %}
			<div class="saved-messages-list">
				<div class="card " style="width: 480px;margin-left: 20px;">
				    <div class="card-body card-body-middle mt-6">
				      <div class="modal fade" id="exampleModalCenter2" tabindex="-1" role="dialog"
				        aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
				        <div class="modal-dialog modal-dialog-centered" role="document">
				          <div class="modal-content">
				            <div class="modal-header">
				              <h5 class="modal-title" id="exampleModalLongTitle">Post Comment</h5>
				              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				                <span aria-hidden="true">&times;</span>
				              </button>
				            </div>
				            <div class="modal-body">
				              <div class="comments-container">

				              </div>
				              <form method="post">
				                {% csrf_token %}
				                {{ comment_form|crispy }}
				                <div class="modal-footer">
				                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				                  <button type="submit" class="btn btn-primary">Post</button>
				                </div>
				              </form>
				            </div>
				          </div>
				        </div>
				      </div>
				      <div class="user-post-details" style="display: flex;justify-content: space-between;">
				        <div style="display:flex;">
				          <img class="post-img" src="{{post.owner.image.url}}"
				          style="width:50px;height: 50px; object-fit: cover;border-radius: 50%;">
				          <h5 class="card-title" style="display:flex;flex-direction: column; margin-top: 5px;"><a href="{% if request.user == post.owner %}{% url 'base:dashboard' post.owner.name|slugify post.owner.pk %}{% else %}{% url 'base:user-profile-showcase' post.owner.name post.owner.pk %}{% endif %}" style="color: black;">{{ post.owner.name }}</a><a href="{% url 'base:explore-post' post.post_id %}"><small
				            class="text-muted">{{ post.pub_date }}</small></a></h5>
				        </div>
				        {% if request.user == post.owner %}
				          <div class="dropdown">
				            <i class="fas fa-ellipsis-h" id="dropdownMenuLink" onmouseover="this.style.color='blue'" onmouseout="this.style.color='black'" style="font-size:20px;cursor: pointer;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>

				            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="margin-left: -140px;">
				              <a class="dropdown-item" href="{% url 'base:edit-post' post.post_id request.user.pk %}"><i class="fas fa-edit"></i> Edit</a>
				              <a class="dropdown-item" href="{% url 'base:delete-post' post.post_id request.user.pk %}"><i class="fas fa-trash-alt"></i> Delete</a>
				              <a class="dropdown-item" href="{% url 'base:saved-messages-detail-create' 'post' post.post_id %}"><i class="far fa-bookmark"></i>  Save Post</a>
				              <a class="dropdown-item" id="copyPostLink" style="cursor:pointer;"><i class="fas fa-link"></i> Copy link</a>
				            </div>
				          </div>
				        {% else %}
				          <div class="dropdown">
				            <i class="fas fa-ellipsis-h" id="dropdownMenuLink" onmouseover="this.style.color='blue'" onmouseout="this.style.color='black'" style="font-size:20px;cursor: pointer;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>

				            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="margin-left: -140px;">
				              <a class="dropdown-item" href="{% url 'base:saved-messages-detail-create' 'post' post.post_id %}"><i class="far fa-bookmark"></i>  Save Post</a>
				              <a class="dropdown-item" id="copyPostLink" style="cursor:pointer;"><i class="fas fa-link"></i> Copy link</a>
				                <input type="text" value="{{request.get_host}}/posts/post-{{post.post_id}}" id="copyPostLinkValue" style="display:none;">
				            </div>
				          </div>
				        {% endif %}
				      </div>
				      <p class="card-text">{{ post.text }}</p>
				      {% if post.photo %}
				      <img class="card-img-bottom" src="{{ post.photo.url }}" alt="Card image cap">
				      {% elif post.video %}
				      <video style="width: 100%;" controls>
				        <source src="{{post.video.url}}" type="video/{{post.video|get_extension}}">
				      </video>
				      {% endif %}
				    </div>
				    <div class="card-footer bg-white">
				      {% for comment in post.post_comment.all %}
				      <b>
				        {% if comment.user != None %}
				          {{comment.user}}
				        {% else %}
				          {{comment.anon_user}}
				        {% endif %}
				      </b>
				        {% for c in comment.comment.all|dictsort:"date" %}
				          <p>{{c.content}} <em> {{c.date}}</em></p>
				        {% endfor %}
				      {% endfor %}
				      <form method="post" action="{% url 'base:post-comment-view' post.post_id %}">
				        {% csrf_token %}
				        <input type="text" name="comment-text" style="width:380px;">
				        <button style="height:30px;width: 50px;border: 0;border-radius: 5px;background-color: blue;color: white;" type="submit">Post</button>
				      </form>
				      <hr>
				      <div class="row">
				        <div class="col-sm d-flex justify-content-center">
				          <form method="get">
				          <a href="/like/{{post.post_id}}/" style="color:black;">
				            {% if request|filter_user%}
				              {% if post.likes.all %}
				                <i class="fa{{post.likes.all|filter_like}} fa-thumbs-up" style="font-size: 30px;"></i>
				              {% else %}
				                <i class="far fa-thumbs-up" style="font-size: 30px;"></i>
				              {% endif %}
				            {% endif %}
				          </a>
				          <em>{{post.likes.all.count}}</em>
				          </form>
				        </div>
				        <div class="col-sm  d-flex justify-content-center" style="color:black;" data-toggle="modal"
				          data-target="#exampleModalCenter2" id="comment">
				          <i class="far fa-comments" style="font-size: 30px;"><input type="hidden" value="{{post.post_id}}"></i>
				        </div>
				        <div class="col-sm d-flex justify-content-center"><a href="#" style="color:black;"><i
				              class="far fa-share-square" style="font-size: 30px;"></i></a></div>
				      </div>
				    </div>
				</div>
			</div>
		{% endfor %}
	{% endfor %}
{% endblock %}

frontend/templates/pages/errors.html
{% extends "base.html" %}

{% block content %}
	<h1 style="text-align: center;margin-top: 200px;">{{error}}</h1>
{% endblock %}

frontend/templates/pages/user_profile_showcase.html
{% extends "base.html" %}

{% block content %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                            <img src="{{user.image.url}}" alt=""/>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                        {{user.name}}
                                    </h5>
                                    <h6>
                                        {{user.profession}}
                                    </h6>
                                    <p class="proile-rating">RANKINGS : <span>8/10</span></p>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="posts-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Posts</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="articles-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Articles</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2" style="display: flex;margin-left: -200px;">
                        <div style="margin-left: 5px;">
                            <a href="{% url 'base:appointment' user.id %}"><button class="btn btn-secondary" type="button">Make Appointment</button></a>
                        </div>
                        <div style="margin-left: 5px;">
                            <a href="/chat/{{user.pk}}"><button class="btn btn-outline-primary" type="button">Message</button></a>
                        </div>
                        <div style="margin-left: 5px;">
                            <a href="{% url 'base:follow' user.name|slugify user.pk %}">
                                {% if followed %}
                                    <button type="button" class="btn btn-outline-primary">Unfollow</button>
                                {% else %}
                                    <button class="btn btn-primary" type="button">Follow</button></a>
                                {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-work">
                            <p>BIO</p>
                            <span>{{user.bio}}</span>
                        </div>
                    </div>
                    <div class="col-md-8" style="">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="home-tab">
				    <div class="row">
                                        {% if posts|length > 0 %}
                                            {% for post in posts %}
					    	<div class="card" style="">
    	                                            {% if post.text %}
                                                        <p>{{post.text}}</p>
                                                    {% endif %}
                                                    <small class="text-muted">{{post.pub_date}}</small>
                                                    {% if post.photo %}
						    
						    <img src="{{media_url}}{{post.photo}}" style="max-width: 500px;max-height: 500px;">
                                                    {% endif %}
    	                                        </div>
                                            {% endfor %}
                                        {% else %}
                                            <h1>No posts yet</h1>
                                        {% endif %}
                                    </div>
                                            
                            </div>
                            <div class="tab-pane fade" id="articles" role="tabpanel" aria-labelledby="profile-tab">
                                {% if articles|length > 0 %}
                                    {% for article in articles %}
                                        <div class="row">
                                            <div class="col-md-6" style="width: 300px;">
                                                <label style="width: 300px;"><a href="{% url 'base:article-detail' article.id %}" style="color:black;width: 300px;word-wrap: break-word;">{{article.headline}}</a></label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{article.date}}</p>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% else %}
                                    <h1>No articles yet</h1>
                                {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>           
        </div>
{% endblock %}